stages: 
  - test 
  - deploy

test:
  tags:
    - docker
  image: python:alpine
  stage: test
  services:
    - name: redis:6-alpine
      alias: db
  script:
    - export PYTHONPATH=/usr/lib/python3.8/site-packages
    - apk add --update --no-cache py3-numpy
    - pip install -r requirements.txt
    - python -m coverage run -m pytest
    - python -m pytest -v

deploy_dev:
  tags:
    - shell_dev
  stage: deploy
  only:
    - dev
  script:
    - export APP_PORT=8080
    - export FRONT_END_URL="http://cloud-vm-43-101.doc.ic.ac.uk"
    - docker-compose -p dev_backend down --rmi local
    - docker-compose -p dev_backend up --build -d

deploy_prod:
  tags:
    - shell_prod
  stage: deploy
  only:
    - master
  script:
    - export APP_PORT=8080
    - export FRONT_END_URL="http://cloud-vm-43-100.doc.ic.ac.uk"
    - docker-compose -p prod_backend down --rmi local
    - docker-compose -p prod_backend up --build -d
