stages: 
  - test
  - deploy

test:
  tags:
    - shell_dev
    - shell_prod
  stage: test
  script:
    - export APP_PORT=8080
    - export WORDS_API_URL="http://cloud-vm-43-108.doc.ic.ac.uk"
    - ./run_tests.sh

deploy_dev:
  tags:
    - shell_dev
  stage: deploy
  only:
    - dev
  script:
    - export APP_PORT=8080
    - export FRONT_END_URL="http://cloud-vm-43-100.doc.ic.ac.uk"
    - export WORDS_API_URL="http://cloud-vm-43-108.doc.ic.ac.uk"
    - docker-compose -p dev_backend down --rmi local --remove-orphans
    - docker-compose -p dev_backend up --build -d

deploy_prod:
  tags:
    - shell_prod
  stage: deploy
  only:
    - master
  script:
    - export APP_PORT=8080
    - export FRONT_END_URL="http://cloud-vm-43-101.doc.ic.ac.uk"
    - export WORDS_API_URL="http://cloud-vm-43-108.doc.ic.ac.uk"
    - docker-compose -p prod_backend down --rmi local --remove-orphans
    - docker-compose -p prod_backend up --build -d
