version: "3.7"
services:
  web:
    build: .
    depends_on:
      - "redis"
      - "mongo"
    environment:
      - FRONT_END_URL
    ports:
      - ${APP_PORT}:5000
  redis:
    image: redis:6-alpine
  mongo:
    image: bitnami/mongodb:5.0
