version: "3.7"
services:
  web:
    build: .
    depends_on:
      - "redis"
      - "mongo"
    environment:
      - FRONT_END_URL
    ports:
      - ${APP_PORT}:5000
    # volumes:
    #   - ${FIREBASE_ADMINSDK_KEY}:/usr/src/app/keys/themed-activity-book-firebase-adminsdk.json
  redis:
    image: redis:6-alpine
  mongo:
    image: bitnami/mongodb:5.0
